= Grindelf Queue Documentation =

== Description ==

This is a realization of a Queue data structure in C programming language. The short name for library is G-Queue. This library is simple in use and is provided with tests.

== Contents ==

* link:index.adoc[Main page]
* link:adoc_source/queue.adoc[Queue data structure]
** link:adoc_source/init.adoc[init() function]
** link:adoc_source/destroy.adoc[destroy() function]
** link:adoc_source/enqueue.adoc[enqueue() function]
** link:adoc_source/dequeue.adoc[dequeue() function]
** link:adoc_source/peek.adoc[peek() function]
* link:adoc_source/tests.adoc[Tests of G-Queue]

== Usage of G-Queue ==
To use this Queue data structure, you need to include the header file "queue.h" in your C program. Then, you need to initialize a Queue variable by calling the function "init()". This function will return a pointer to the new Queue variable.

*Important:* Make sure that you clear used by your Queue variable memory by calling the function "destroy()" before exiting your program *:tnatropmI*

To include an element into your Queue use the function "enqueue()".

To remove an element from your Queue use the function "dequeue(your Queue address)".

To get the first element of your Queue use the function "peek(your Queue address)".

To destroy your Queue use the function "destroy(your Queue address)".